export default [
  { method: 'GET', path: '/dashboard', handler: 'figurines.dashboard', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'GET', path: '/requests', handler: 'figurines.find', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'GET', path: '/requests/:requestId', handler: 'figurines.detail', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'GET', path: '/orders/:orderId', handler: 'figurines.orderDetail', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'PUT', path: '/requests/:requestId', handler: 'figurines.requestUpdate', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'PUT', path: '/requests/:requestId/offers', handler: 'figurines.saveOffer', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'POST', path: '/requests/:requestId/offers/:offerId/present', handler: 'figurines.presentOffer', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'POST', path: '/requests/:requestId/offers/:offerId/withdraw', handler: 'figurines.withdrawOffer', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'PUT', path: '/orders/:orderId/operation', handler: 'figurines.operation', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'GET', path: '/returns', handler: 'figurines.returnList', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'PUT', path: '/returns/:id', handler: 'figurines.returnDecision', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'GET', path: '/requests/:requestId/photos/:assetKey', handler: 'figurines.photo', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'GET', path: '/notifications', handler: 'figurines.notifications', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'POST', path: '/notifications/:id/retry', handler: 'figurines.retryNotification', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'GET', path: '/account-deletions', handler: 'figurines.deletionList', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'PUT', path: '/account-deletions/:id', handler: 'figurines.deletionDecision', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'GET', path: '/retention/preview', handler: 'figurines.retentionPreview', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'POST', path: '/retention/execute', handler: 'figurines.retentionExecute', config: { policies: ['admin::isAuthenticatedAdmin'] } },
  { method: 'GET', path: '/guest-claims', handler: 'figurines.guestClaims', config: { policies: ['admin::isAuthenticatedAdmin'] } },
];
